import { signIn } from 'next-auth/react';
import './globals.css'
import Link from "next/link";
import { FaGithub } from "react-icons/fa";
import NavBar from '@/component/NavBar';
import { cookies } from 'next/headers'


export const metadata = {
  title: 'Eighteen',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    let cookie = cookies().get('mode')

  return (
      <html lang="en">
      <body className={
          cookie != undefined && cookie.value == 'dark'
              ? 'dark-mode'
              : ''}
      >

        <NavBar/>
        {/* <div className={"navbar"}>
          <Link href={"/"}>Home</Link>
          {
            session ?
            <Link href={"/mypage"}>MyPage</Link> 
            :<Link href={"/login"}>Login</Link>
          }
        </div> */}
        <div className={"wrap"}>
          {children}
        </div>
        <div className={"footer"}>
          <Link href={"https://github.com/SultanLee/eighteen"}><FaGithub /></Link>
        </div>

      </body>
      </html>
  )
}
